### ISSUE TITLE
Lexer: Numbers

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/slide#1]
First, we need to build a lexer for slide. Let's start with tokenizing numbers. The idea is to have an entry point, say a "lex" function, that takes a string and outputs tokens.

```
"1 2 3" -> Real(1) Real(2) Real(3)
"1.2 5" -> Real(1.2) Real(5)
"1.2.3" -> Real(1.2) Dot Real(3)
```

@luke-bhan would you like to take the lead on this?

**Comment by ayazhafiz** [comment]
@luke-bhan any updates?

**Comment by luke-bhan** [comment]
Writing unit tests now

**Comment by luke-bhan** [comment]
am i good to merge?

**Comment by ayazhafiz** [comment]
sure

________________________________
От: Luke Bhan <notifications@github.com>
Отправлено: Wednesday, March 18, 2020 7:51:26 PM
Кому: ayazhafiz/slide <slide@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Author <author@noreply.github.com>
Тема: Re: [ayazhafiz/slide] Lexer: Numbers (#1)


am i good to merge?

**Comment by luke-bhan** [comment]
ok, next we need to write something that puts these tokens into an ast right?

**Comment by ayazhafiz** [comment]
@luke-bhan yeah, we need to write a parser next. I can do an implementation or you can research and find one you like. Or we can use a parser generator. What would you prefer?

**Comment by luke-bhan** [comment]
how busy are you? I would love to write it myself to just learn its just gonna take me a while. Otherwise if you wanna do it thats fine too.

**Comment by ayazhafiz** [comment]
How about the following: choose a parsing strategy and then we will implement it together. There are many types of parser, feel free to choose whatever you feel is the most interesting. If you need help finding more info lmk

**Comment by luke-bhan** [comment]
heres an older parser that I am using as a base to start learning:
https://www.mat.univie.ac.at/~neum/ms/DynGenPar-DML.pdf
