### ISSUE TITLE
Evaluator 

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#10]
Build an evaluator using an iterator and a visitor class.

**Comment by luke-bhan** [comment]
design question: If we have a variant Expr, and then sub variants BinOp, UnOp, Float etc. Do we want to write just one visitor for Expr that matches, or do we want to visitor levels such that a visit to an Expr just calls the appropriate Visit based on its enum variant.

**Comment by ayazhafiz** [comment]
visitor levels is better IMO

________________________________
От: Luke Bhan <notifications@github.com>
Отправлено: Monday, April 27, 2020 7:39:39 PM
Кому: ayazhafiz/slide <slide@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Mention <mention@noreply.github.com>
Тема: Re: [ayazhafiz/slide] Evaluator (#10)


design question: If we have a variant Expr, and then sub variants BinOp, UnOp, Float etc. Do we want to write just one visitor for Expr that matches, or do we want to visitor levels such that a visit to an Expr just calls the appropriate Visit based on its enum variant. @ayazhafiz<https://github.com/ayazhafiz>

**Comment by luke-bhan** [comment]
also what exactly does the plus op do? Does it make a negative positive or is it a no op
