### ISSUE TITLE
setup a testing framework

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#104]
I think something similar to rustfmt could be super clean here. For example we would say
"5+5" in the src file and "10" in the target file for an evaluator.

**Comment by luke-bhan** [comment]
I would like to take this one after I finish the gcd reduction.

**Comment by ayazhafiz** [comment]
Sounds good. Just a suggestion, maybe you don't need a source/target file idea. Just separate the source and result with some delimiter, maybe like `---`

**Comment by luke-bhan** [comment]
I agree, its annoying the way rust has two files.

**Comment by ayazhafiz** [comment]
The UI I am thinking of is configuring tests in the form

```
===in
1 + 2 + 3
===in

===stdout
6
===stdout

===stderr
===stderr
```

With some nice flag like `--green` to auto-generate the outputs
