### ISSUE TITLE
Flatten Multiplication/Division expression

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#106]
This may not need to be done before 0.1, but I think it would be nice considering adding and subtraction is already implemented and the framework shouldn't take to long.

**Comment by ayazhafiz** [comment]
Let's revisit this when we finish the rest of the stuff in 0.1, putting in backlog for now

**Comment by ayazhafiz** [comment]
/slide "x(x + 2 * 3) / (x + 6)"

This is the example in our readme. I feel like we should have it working before 0.1.

**Comment by ayazhafiz** [comment]
I think flattening should be enough

**Comment by ayazhafiz** [comment]
ugh i spent all day today thinking about #49 and got nowhere, does someone want to try this?

If not I will work on it soon
