### ISSUE TITLE
GitHub Bot Test Dispatch

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/slide#118]
Another fun and useful idea: add a GitHub Bot that will run slide and print its output in a new comment. https://github.com/peter-evans/slash-command-dispatch could be used for this, they already provide the heavy lifting.

So a comment would be like

```
/slide -o s-expression "1 + 2 + 3"
```

and the bot should comment

```
Output for `slide -o s-expression "1 + 2 + 3"`:

6
```

**Comment by ayazhafiz** [comment]
followup: `/slide -o s-expression "1 + 2 + 3" EXPECT 6` opens a new issue if the output is not 6

**Comment by ayazhafiz** [comment]
> slide "1 + 2" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644547625)

```
3
```

[Command run output][1]
[1]:

**Comment by ayazhafiz** [comment]
> slide -o s-expression "a * b" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644550526)

```
(* a b)
```

[Command run output][1]

[1]:

**Comment by ayazhafiz** [comment]
/slide -odebug "1 + 2 * 3 ^ 4 % 5"

**Comment by ayazhafiz** [comment]
> slide -odebug "1 + 2 * 3 ^ 4 % 5" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644556035)

```
Const( 3.0, )
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/runs/136847800

**Comment by ayazhafiz** [comment]
/slide -odebug "1 + 2 * 3 ^ 4 % 5" --parse-only

**Comment by ayazhafiz** [comment]
> slide -odebug "1 + 2 * 3 ^ 4 % 5" --parse-only (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644559980)

```
Expr( BinaryExpr( BinaryExpr { op: Plus, lhs: Const( 1.0, ), rhs: BinaryExpr( BinaryExpr { op: Mod, lhs: BinaryExpr( BinaryExpr { op: Mult, lhs: Const( 2.0, ), rhs: BinaryExpr( BinaryExpr { op: Exp, lhs: Const( 3.0, ), rhs: Const( 4.0, ), }, ), }, ), rhs: Const( 5.0, ), }, ), }, ), )
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/136853629

**Comment by ayazhafiz** [comment]
> slide "5 @ 2" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644560034)

```
error: Invalid token | 1 | 5 @ 2 | ^ | - note: token must be mathematically significant |
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/136854205

**Comment by ayazhafiz** [comment]
> slide "5 @ 2" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644564764)

```
error: Invalid token
 |
1 | 5 @ 2
 | ^
 | - note: token must be mathematically significant
 |
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/136861487

**Comment by ayazhafiz** [comment]
> slide "5 @ 2" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644570774)

```
error:%20Invalid%20token
%20%20|
1%20|%205%20@%202
%20%20|%20%20%20^
%20%20|%20%20%20-%20note:%20token%20must%20be%20mathematically%20significant
%20%20|
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/136873158

**Comment by ayazhafiz** [comment]
> slide "5 @ 2" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644761012)

```
error:\\ Invalid\\ token
\\ \\ |
1\\ |\\ 5\\ @\\ 2
\\ \\ |\\ \\ \\ ^
\\ \\ |\\ \\ \\ -\\ note:\\ token\\ must\\ be\\ mathematically\\ significant
\\ \\ |
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137233075

**Comment by ayazhafiz** [comment]
> slide  (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644767047)

```
error:\ The\ following\ required\ arguments\ were\ not\ provided:
\ \ \ \ <program>

USAGE:
\ \ \ \ slide\ <program>\ -o\ <output-form>

For\ more\ information\ try\ --help
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137240327

**Comment by ayazhafiz** [comment]
> slide  (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644770310)

```
error: The following required arguments were not provided:
 <program>

USAGE:
 slide <program> -o <output-form>

For more information try --help
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137246107

**Comment by ayazhafiz** [comment]
> slide  (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644776365)

```
error:Thefollowingrequiredargumentswerenotprovided:
<program>

USAGE:
slide<program>-o<output-form>

Formoreinformationtry--help
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137255145

**Comment by ayazhafiz** [comment]
> slide  (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644785163)

```
error:Thefollowingrequiredargumentswerenotprovided:
<program>

USAGE:
slide<program>-o<output-form>

Formoreinformationtry--help
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137268301

**Comment by ayazhafiz** [comment]
> slide slide "5 +" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644794580)

```
error:\ Found\ argument\ '5\ +'\ which\ wasn't\ expected,\ or\ isn't\ valid\ in\ this\ context

USAGE:
\ \ \ \ slide\ [FLAGS]\ [OPTIONS]\ <program>

For\ more\ information\ try\ --help
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137290451

**Comment by ayazhafiz** [comment]
> slide "5 +" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644803998)

```
error:\Expected\an\expression,\found\end\of\file
\\|
1\|\5\+\
\\|\\\\^\expected\an\expression
\\|
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137312653

**Comment by ayazhafiz** [comment]
> slide "5 +" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644855645)

```
error: Expected an expression, found end of file
  |
1 | 5 + 
  |    ^ expected an expression
  |
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137394160

**Comment by ayazhafiz** [comment]
@luke-bhan yoo it worked!

**Comment by ayazhafiz** [comment]
It's slow but it works :)

**Comment by ayazhafiz** [comment]
/slide -odebug "1 + 2 * ^ - 7 + *"

**Comment by luke-bhan** [comment]
lets fucking go!!!!

**Comment by ayazhafiz** [comment]
> slide -odebug "1 + 2 * ^ - 7 + *" (https://github.com/ayazhafiz/slide/issues/118#issuecomment-644859588)

```
Token { ty: Exp, span: Span { lo: 8, hi: 9 } }
thread 'main' panicked at 'internal error: entered unreachable code', libslide/src/parser.rs:124:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[Command run output][1]

[1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/137405177

**Comment by ayazhafiz** [comment]
/slide -odebug "1 + 2 * ^ - 7 + *"

**Comment by ayazhafiz** [comment]
marking as done

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2

**Comment by ayazhafiz** [comment]
/slide "x * x" expect? x ^ 2
