### ISSUE TITLE
Precedence Issues on Division

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#17]
Issue with division 1/2/3 yields (/ 1 (/ 2 3)) when it should yield (/ (/ 1 2) 3)

**Comment by luke-bhan** [comment]
@ayazhafiz  the fact that this is designed with macros makes it fucking impossible to debug. In the future, lets only use macros once we are sure all the bugs are removed

**Comment by ayazhafiz** [comment]
Well you can unwrap the macros or place print in the macro. Alternatively, pull the function you want out of the macro.

**Comment by ayazhafiz** [comment]
@luke-bhan the problem is that we always fold expressions to the left when we should fold them to the right.

`1 + 2 + 3 -> 1 + (2 + 3)`, but we should really be doing `(1 + 2) + 3`.

Let me know if you need help implementing a fix.

**Comment by luke-bhan** [comment]
Ok, So I have a fix, but I still don't understand how to implement this on our current version. 
We need to use a while let statement to implement our pattern matching as such:

'''
    fn add_sub_term(&mut self) -> box<expr> {
        let mut node = self.mul_divide_mod_term();
        while let tokentype::plus | tokentype::minus = self.token().token_type {
            let op = self.token().clone();
            self.advance();
            node = box::new(expr::binop(binop {
                op,
                lhs: node,
                rhs: self.mul_divide_mod_term(),
            }));
        }
        node
    }

    fn mul_divide_mod_term(&mut self) -> box<expr> {
        let mut node  = self.exponent_term();
        while let tokentype::mult | tokentype::div | tokentype::mod = self.token().token_type {
            let op = self.token().clone();
            self.advance();
            node = box::new(expr::binop(binop {
                op,
                lhs: node,
                rhs: self.exponent_term(),
            }));
        }
        node
    }
'''

**Comment by luke-bhan** [comment]
So I don't think our macro actually will work because we use the same simple function for all types when this specifically requires we run a while for that type

**Comment by ayazhafiz** [comment]
That's fine, you can expand the macro out.

**Comment by luke-bhan** [comment]
is it possible to only expand part of the macro? like i don't need to for exp and num

**Comment by ayazhafiz** [comment]
yeah just copy it out and create a new function.

**Comment by luke-bhan** [comment]
I am struggling with getting the operator from this try_from in a loop. Basically I need to continually update op while op matches with plus or minus

**Comment by ayazhafiz** [comment]
Just clone the operator. There is another way to do this, which you may
find more elegant:
https://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/.
This is an approach very similar to what the last ISD assignment does.
