### ISSUE TITLE
Parser: LL parser

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#3]
Ok, we are actually going to use an LL parser. Recursion descent is a general form of the ll parser that requires backtracking and therefore isn't linear (its exponential), one could say its a LL(k) parser where k can be any number. K signifies how many tokens in advance the parser needs to look at in order to parse the current token. Meanwhile, if we constrain our grammar by precedence rules, we can avoid left recursion and left factoring and write a parser called a predictive parser that is LL(1). This will result in a linear time parser from what I understand. This is all i generally know for now and will take much much more research before I can ever properly contribute. @ayazhafiz Do you wanna begin by trying to define a grammatical set of rules for our "math" language. Like for example, we will need to parse all parentheses and brackets first, if I am not mistaken. I think a good strategy should be defining a 3 types of symbols: operators (+, -, =), numbers (2, 2.0, 3.3), and parentheses/brackets almost exactly like how you did it in rcalc.

**Comment by luke-bhan** [comment]
so our grammer is just a regular grammar and not context free since we dont have if statements or classes correct?

**Comment by ayazhafiz** [comment]
I believe we will be a context free grammar. I'm not sure we can raise our grammar to a regular one - for example, how would we express `1 + 2`?

```
Expr -> Expr + Expr
      | Number
```

I'm not sure we could linearize this any way so that it is either left or right recursive. It may have to be both.

**Comment by ayazhafiz** [comment]
Grammar:

```
<Number> -> <Digit><Number>
          | +<Number>
          | -<Number>
          | .<Number>

<Op> -> +
      | -
      | *
      | /
      | %
      | ^
      | =

<Variable> -> [a-zA-Z0-9_]*

<Expr> -> <Expr> <Op> <Expr>
        | (<Expression>)
        | [<Expression>]
        | {<Expression>}
        | <Number>
        | <Variable>
```

@luke-bhan can you take a look? Do you think we should add support for functions, or later on?

**Comment by luke-bhan** [comment]
we need to support assignment though, so that should be = and == should be an operator. Even if we don't do functions yet I think we should still include = so we can assign. Also, you forgot parentheses or we can do those later

**Comment by luke-bhan** [comment]
@ayazhafiz

**Comment by ayazhafiz** [comment]
Well I was thinking `1 = 2` is an expression where `=` is the operator. What do you think?

Also, parantheses are in this grammar. Check the second option of `Expr`

**Comment by luke-bhan** [comment]
I’m confused. In your above example, is = assigning 1 to 2 or is it comparing

**Comment by luke-bhan** [comment]
Or is it just a user defined op

**Comment by ayazhafiz** [comment]
I assume we should go with comparison, since that is typically what it is in math expressions.

The other thing is it could be context dependent.

```
x = 1 # assignment
integral_0^1 x dx = 1/2 # comparison because the left side is an expression, not a variable
```

**Comment by luke-bhan** [comment]
Let’s just stick with comparison then- no context dependence for now

**Comment by ayazhafiz** [comment]
Do you want to add `==`?

**Comment by luke-bhan** [comment]
Yea sorry. Add == otherwise variables don’t make sense in our code

**Comment by luke-bhan** [comment]
I can add it tomorrow it’s a little late tonight

**Comment by ayazhafiz** [comment]
alright will do. have a good night

________________________________
От: Luke Bhan <notifications@github.com>
Отправлено: Sunday, March 29, 2020 11:41:09 PM
Кому: ayazhafiz/slide <slide@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Assign <assign@noreply.github.com>
Тема: Re: [ayazhafiz/slide] Parser: LL parser (#3)


I can add it tomorrow it’s a little late tonight

**Comment by luke-bhan** [comment]
Ok a few more thoughts. Sorry I have been awall. Do you think we should call numbers and variables just one class that are known as identities. But number's are just constant identities so they can never be assigned or is that too complex

**Comment by ayazhafiz** [comment]
I think it is better to distinguish between the two. Anyway it would just be two cases to handle, so I don't think it's a big deal. Also we can do optimization with numbers that we can't necessarily do with variables.

**Comment by luke-bhan** [comment]
I think we need to completely rewrite the grammar @ayazhafiz. We need to remove left recursion and left factoring and introduce precedence. 
If it's ok, I plan on taking the lead on this. LMK your thoughts

**Comment by ayazhafiz** [comment]
Sounds good! Excited to see it :)

**Comment by luke-bhan** [comment]
Ok, I've been working this out for a while before I event commented lol. Here's what I came up with:
```
Using what you defined above as numbers and variables, we have
<expr>    -> <e1> <e1_tail>
<e1>      -> <e2> <e2_tail>
<e1_tail> -> '+' <e1> <e1_tail> / '-' <e1> <e1_tail>   
           | empty 
<e2>      -> <e3> <e3_tail>
<e2_tail> -> '*' <e2> <e2_tail> / '/' <e2> <e2_tail> / '%' <e2> <e2_tail>
           | empty
<e3>      -> <e4> <e4_tail>
<e3_tail> -> <e3> '^' <e3_tail>
           | empty
<e4>      -> '(' <expr> ')' / '[' <expr> ']' / '-' <e4> / number / variable
<e4_tail> -> = <e4> <e4_tail>
           | empty
```
What do you think @ayazhafiz

**Comment by ayazhafiz** [comment]
Why can tails be empty? also e4_tail should include + <e4>

**Comment by luke-bhan** [comment]
consider the problem 2+2; 
we will never need e2_tail, or e3_tail, or e4_tail. Only e1_tail. That's why they can be empty. Why does e4_tail need +?

**Comment by ayazhafiz** [comment]
I’m confused. Then why can e1_tail be empty? Also in those cases, there is nothing saying that the tail has to be used right. 2+2 is just an e4 expansion + e4 expansion. the tails are never expanded.

<e4> needs a + <e4> for congruency with - <e4>

**Comment by luke-bhan** [comment]
e1 has to be able to never be used just like the others. So if it’s 2*2 then only the e2 tail is used. And the - in e4 is a negation operator. We don’t technically need it since you defined numbers to be negative, it would only be used for variables. In that case we wouldn’t need a + op for e4

**Comment by ayazhafiz** [comment]
Yes, and the e2 tail is used only because it fits in an expansion. We never expand the e1 tail to be “empty” in that context. Does that make sense? Am I missing something?

For example in 1+1, I can expand apply a parse tree from expansion of the grammar <e4> + <e4>. At no point do I need to expand a grammar to “empty”.

I think we should include a positive operation in addition to negation.

________________________________
От: Luke Bhan <notifications@github.com>
Отправлено: Sunday, April 5, 2020 8:54:44 PM
Кому: ayazhafiz/slide <slide@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Mention <mention@noreply.github.com>
Тема: Re: [ayazhafiz/slide] Parser: LL parser (#3)


e1 has to be able to never be used just like the others. So if it’s 2*2 then only the e2 tail is used. And the - in e4 is a negation operator. We don’t technically need it since you defined numbers to be negative, it would only be used for variables. In that case we wouldn’t need a + op for e4

**Comment by luke-bhan** [comment]
I think we are just getting tripped up over semantics. I see what your saying, and I think my way of saying empty was trying to emphasize that the certain tail wasn't used.

**Comment by ayazhafiz** [comment]
I don't think that's correct though. Because then `1 +` is a valid expression under this grammar, which it is not.

**Comment by luke-bhan** [comment]
1+ is not a valid expression. 1+ is going to call <e1> <e1_tail> which expands to <e1> '+' <e1> <e1_tail>. Since <e1> can never be an empty expression, then we will know 1+ is not valid.

**Comment by ayazhafiz** [comment]
Okay, I see what you are saying. My bad. There is another problem with this though, and that is for example `1 + 2 * 3` is not a valid expression.

**Comment by luke-bhan** [comment]
It is a valid expression. I'm writing the parser now which should clear things up. gimme an hour or two.

**Comment by luke-bhan** [comment]
ok updated commit is in parser branch. I've gotten to the point where I have the basic framework written. Can you implement adding the node to the tree and building the head. I am a little confused on how to do that with boxes? Also, feel free to change the framework if you don't like how I did it. I based it off this: http://www.cs.fsu.edu/~lacher/courses/COP4020/assigns/proj2a.html. 
@ayazhafiz
