### ISSUE TITLE
Optimization platform

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/slide#7]
We should begin work on the expression optimization platform now that we have an AST built. Here is the rough architecture we had originally designed for slide:

![60360630726__F5CA088E-3C3E-4BE6-860C-13B44BAA3F87](https://user-images.githubusercontent.com/20735482/80169413-2dea2980-859a-11ea-9a92-cc6691ac4e5c.jpg)

I think we need to at least think about the following things as we go forward:

- [ ] Do we need a normalizer to express expressions in a common format? This would allow us to rearrange expressions safely when they can be to "align" common items like variables, e.g. `(a + b) - (b + a) -> (a + b) - (a + b)`. Maybe this will make some optimizations easier, but I am not convinced of it.
- [ ] How do we design a platform where we can easily plug optimizations in and out? We will need to do this as a some kind of rule-based registry, but what does that actually look like?
- [ ] What algorithms do we use to evaluate an expression and determine whether it can be optimized? Should this algorithm be defined as part of a rule, or should a rule be agnostic to the algorithm we use to evaluate a rule?

**Comment by ayazhafiz** [comment]
@luke-bhan do you want to hop on a call sometime soon to chat about this?

**Comment by luke-bhan** [comment]
im free now

**Comment by ayazhafiz** [comment]
I'm not. What about this weekend?

**Comment by ayazhafiz** [comment]
text me xoxo gossip girl 💋

**Comment by luke-bhan** [comment]
im free pretty much anytime lol

**Comment by ayazhafiz** [comment]
@luke-bhan I think one optimization we can start with is associativity. If an expression is unevaluatable, we check if it can be rewritten in an associative manner and recompute it. Does that make sense?

**Comment by luke-bhan** [comment]
yes, so if we have an issue like 3+a+4, we will check if a+3+4 is computable

**Comment by luke-bhan** [comment]
Do you agree we can consider an optimization to be smaller by the number of ops it has? That’s the way we can tell?

**Comment by luke-bhan** [comment]
Also this gonna make the program run a lot slower Bc we’re gonna have need tokens Combination available switches like tCa

**Comment by ayazhafiz** [comment]
> yes, so if we have an issue like 3+a+4, we will check if a+3+4 is computable

Well that is commutativity, but yeah. Idea stays.

> Do you agree we can consider an optimization to be smaller by the number of ops it has? That’s the way we can tell?

Yeah that seems reasonable.

> Also this gonna make the program run a lot slower Bc we’re gonna have need tokens Combination available switches like tCa

Yep it is. But these are tiny operations, the difference is insignificant in terms of real time. What do you mean by tCa?

**Comment by ayazhafiz** [comment]
@luke-bhan friendly ping for the above question: what is tCa?

Anyway, I've been doing some research and as of now I think there are a couple solutions we could consider.

<ol>
<li>Implement a rule-based system to match on expression ASTs ([Resource 1], [Resource 2]). The idea is that we can define a series of transformation rules, like

```
Rule("_0 + _0 * _1", "(1 + _0) * _1") // x + x*a = (1 + x) * a
```

that we then try to pattern match on our generated expression AST. We attempt to match these patterns an indefinite amount of times, until we reach an expression that we have already reduce to (meaning that the expression is no longer reducible).
</li>

<li> Implement a rule-based system, but with a standard evaluation procedure. This is what [Mathematica does]. We implement the rule-based system above, but we also perform a transformation on the mathematical grammar to place it in a form that is easier to pattern match and evaluate partially. Namely, literals are hosted to the right and non-literals are placed in alphabetical order.

```
a + 1 + b + 7 -> 1 + 7 + a + b
```

Observe that this requires creating ASTs with arbitrary arity. For example, the binary operator `+` would need to be expressed with something like `Plus { args: [Expression] }`. The following [example] from the Mathematica reference describes this kind of evaluation in the Mathematica system:

| result | explanation |
|:-|:-|
`2ax+a^2+1` | here is the original expression
`Plus[Times[2,a,x],Power[a,2],1]` | this is the internal form
`Times[2,a,x]` | this is evaluated first
`Times[2,7,x]` | a is evaluated to give 7
`Times[14,x]` | built‐in definitions for Times give this result
`Power[a,2]` | this is evaluated next
`Power[7,2]` | here is the result after evaluating a
`49` | built‐in definitions for Power give this result
`Plus[Times[14,x],49,1]` | here is the result after the arguments of Plus have been evaluated
`Plus[50,Times[14,x]]` | built‐in definitions for Plus give this result
`50+14x` | the result is printed like this

This idea is more along the lines of what I was originally thinking for this project, but I wasn't clever enough to figure out what the rule based system would look like. I think matching ASTs is a very elegant idea.
</li>
</ol>

There is also a [Computer Algebra Book] that I will begin exploring for more ideas.

We can prototype a number of different solutions (and even implement them in parallel) if we wish. I see no reason that we need to have only one parser and one evaluation/optimization platform. Perhaps if we are very optimistic we can have a `BinaryParser` and `ArityParser` that output results varying by the strategies above, and each perform evaluation independently.

@luke-bhan what do you think? Can you review the resources and proposals suggested above and let me know how you want to move forward? Do you have any other ideas?

[Resource 1]: https://stackoverflow.com/a/7542438/6312217
[Resource 2]: http://www.semdesigns.com/products/DMS/SimpleDMSDomainExample.html

[Mathematica does]: https://reference.wolfram.com/language/tutorial/EvaluationOfExpressions.html
[example]: https://reference.wolfram.com/language/tutorial/EvaluationOfExpressions.html#12376

[Computer Algebra Book]: https://www.ukma.edu.ua/~yubod/teach/compalgebra/%5BJoel_S._Cohen%5D_Computer_algebra_and_symbolic_comp(BookFi.org).pdf

**Comment by luke-bhan** [comment]
I really like what mathematical does that so fucking beautiful

**Comment by luke-bhan** [comment]
So generally we're trying to write a transformation engine for simple algebraic expressions correct?

**Comment by ayazhafiz** [comment]
Looks like mathjs uses method (1) to simplify expressions: https://github.com/josdejong/mathjs/blob/develop/src/function/algebra/simplify.js

**Comment by luke-bhan** [comment]
phone died gimme 2 mins sorry.

**Comment by ayazhafiz** [comment]
@luke-bhan use this to get a mathjs session running in Node

```bash
# in slide directory, or wherever
yarn install mathjs
# or npm install mathjs

node
> const mathjs = require('mathjs');
> mathjs.parse('1 + 2');
> // will print result of parse here, you can access fields and such too
```

**Comment by ayazhafiz** [comment]
@luke-bhan and I just discussed next steps for the optimization platform. We're going to go with [method (1)](https://github.com/ayazhafiz/slide/issues/7#issuecomment-623185328) for now, using mathjs's implementation as a reference. Pattern matching is likely the trickiest pattern of this system.

After we show that this is up and running, we can put more work into evaluating contexts defined by assignments.

**Comment by ayazhafiz** [comment]
I spent a few hours looking into how we should implement the rule based system today. I suggest we implement it in the following way:

<ol>
<li>
Define a ruleset that consists of expression mappings, in the form `expr_left -> expr_right`. As a concrete example, `$v + 0 -> $v`.
</li>

<li>
Parse rules into `Rule`s that consist of a left and right expression representing each side of the rule string.

```rust
struct Rule {
  left: Box<Expr>,
  right: Box<Expr>,
}
```
</li>

<li>
Match rules against a target expression, returning a mapping of a rule subexpression to a target subexpression. For instance, if we have a rule `$v + 0 -> $v` matched against `a + 0`, we return the mapping `{$v: a, 0: 0}` (`0: 0` can probably even be elided).

To implement the matching we can just use a Visitor.

Then, we use the mapping to transform the RHS of the rule to the lowered target expression. In the example above, we replace the RHS `$v` using the pattern-matched mapping to obtain `a`. This transformation is also a fairly-trivial visitor that uses the pattern matching context.

Note that this will require us to have a grammar for various items in a pattern match. I propose the following:

| pattern | type |
|-|-|
| \<number> | exact constant |
| $\<var> | variable |
| #\<con> | arbitrary constant |
| _\<name> | arbitrary expression node |

</li>
</ol>

Additionally, there are a couple of things I think we should do as a precursor/in line with this feature:

1. Consolidate `Int` and `Float` expressions as one, maybe just `Constant`. This will make matching a whole lot easier, and we don't need this distinction.

2. Move to using `BigNum`s or some other arbitrary-precision number DS. We will need this in the long term anyway.

@luke-bhan what do you think of this? Any suggestions you have or improvements you think would be good to make? I would like to start on this tomorrow.

**Comment by luke-bhan** [comment]
I agree with the consolidation. But, my question is in building the rules and maybe I can look into math js for this but how does Box<Expr> get filled in a rule. Like what would the term be? Is that the _<name> that you refer to? Also bignum would be a class for values above double precision correct?

**Comment by ayazhafiz** [comment]
> how does Box get filled in a rule. Like what would the term be?

What do you mean by getting filled? An expression is mapped from one form to another. As in the example I showed above, we use the pattern matching to replace `$v` with `0`.  If we can't match it with anything, then the term stays as it was.



> Also bignum would be a class for values above double precision correct?

Yes

**Comment by luke-bhan** [comment]
I mean if we create the Rule v+0 we have to have is such that we have Box<Expr> op = +, rhs = 0, and lhs = ? what is the lhs gonna hold for arbitray v. Also I can get started on a bignum class tonight. I think I will just make an array with arbitray size limit and fill with zeros unless you know of a better way in rust

**Comment by ayazhafiz** [comment]
LHS is an `Expr(Variable)`

**Comment by luke-bhan** [comment]
Also, we should refactor some of our files. I think we need to use some folders so that we can differentiate between visitors with our grammer and our rules. I think you're much better at structuring if you want to do this

**Comment by ayazhafiz** [comment]
> Also I can get started on a bignum class tonight. I think I will just make an array with arbitray size limit and fill with zeros unless you know of a better way in rust

Sadly I think for a BigNum class we will have to use a dependency. Implementing a BigNum properly is pretty difficult (we have to support mult, division, etc), and is a whole project on its own. It's one I'd love to do though, if you're interested ;)

**Comment by ayazhafiz** [comment]
> Also, we should refactor some of our files. I think we need to use some folders so that we can differentiate between visitors with our grammer and our rules. I think you're much better at structuring if you want to do this

Sure, I can do this.

**Comment by ayazhafiz** [comment]
I think we have the basic idea down and have shown that it works, so I'm closing this.
