### ISSUE TITLE
Comparison doesn't work when one value is missing a decimal vector

### ISSUE THREAD

**Issue by timothycobrien** [ayazhafiz/slide#78]
For example, `(1.25 > 1)` should return `true`, but it is returning `false` in this case. Similarly, `(1 < 1.25)` should return `true`, but it returns `false`. 

So it seems to occur whenever the floors of the two values are the same, but one of them is an integer (i.e. equal to its own floor). Need to look at `libslide/src/bignum/compare.rs`

**Comment by timothycobrien** [comment]
I'm totally cool with fixing this, was just curious about which solution we might want to go with here? Seeing two main lines of attack.

## Fix 1
BigNums always have at least one digit for both the non-decimal and decimal sides, making things like 2 or .3 impossible as they would be replaced with 2.0 and 0.3. This would mean modifying the BigNum constructor/possible other methods that might omit a side.

## Fix 2
Just fix the comparison so that when a BigNum with both a non-decimal and decimal is compared to a BigNum without either, the comparator knows to treat an empty vector as a zero. Would juts required modifying `compare.rs`

Thoughts @luke-bhan @ayazhafiz ?

**Comment by luke-bhan** [comment]
Go for it!
Interesting, the first fix you have is actually how I had it implemented before the last commit. 
The reason I stopped the ability to hold the zero was that numbers like 2.0 would cause issues with the fft multiplication. I think the second fix is a much easier one and I would probably do it like that since it avoids extra steps in computation long term for both the add and sub method since you don't have to handle the extra position in the decimal vector.

**Comment by timothycobrien** [comment]
I'm wondering, though, if the second fix doesn't impact future code in similar ways. That is to say, all future code would have to account for this same specific case rather than handling all cases.

**Comment by ayazhafiz** [comment]
I think the second fix is better. We shouldn't rely on the bignum to be in any particular state aside from the ordering of its internal containers. If implementations ever change the comparator should still function as long as the underlying data is of the same form.

@timothycobrien do you want me to add you as a collaborator on the project?

**Comment by timothycobrien** [comment]
That'd be great @ayazhafiz

**Comment by timothycobrien** [comment]
I'll fix this now with the modifications to the bignum ctor
