### ISSUE TITLE
Multiply doesn't work properly with decimals and integers

### ISSUE THREAD

**Issue by timothycobrien** [ayazhafiz/slide#82]
Haven't tried all possible test cases, but here is an illustrative one.

`5 * .5` should be equal to `2.5`, but multiply returns the value `5.02`.

@luke-bhan thoughts?

**Comment by luke-bhan** [comment]
fixing now.

**Comment by luke-bhan** [comment]
Ok, this one is pretty tricky, Basically the vectors are coorect that they are [5, 0] and [0, 5] results in [0, 25] and we should be yielding [25, 0]. I think this may be able to be solved by extending the vectors with extra zeros? I am not really sure here. ideas @timothycobrien

**Comment by timothycobrien** [comment]
I think I need to take a closer look at what's going on, but probably some sort of shifting makes sense

**Comment by timothycobrien** [comment]
Proposal: we switch to using [Toom-Cook](https://en.wikipedia.org/wiki/Toom%E2%80%93Cook_multiplication) which performs better until at least like 40,000 decimal digits in each number. I think it'll be similar than trying to perform FFTs and much of the performance increase is lost when FFTs are actually performed recursively.

Thoughts @ayazhafiz @luke-bhan?

**Comment by luke-bhan** [comment]
Why not both? I mean this entire bignum class is going to get abstracted into a separate repo once your fix to compare is merged so It's not like we should throw away the fft implementation. But I am always down for implementing a new algo! Eventually the core of bignum will probably need to be written as vectors are kinda a slow storage method, but that's down the road.

**Comment by ayazhafiz** [comment]
You guys know way more about this than I do, it all SGTM feel free to implement anything you want :)
