### ISSUE TITLE
Emit documentation only for slide and libslide

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/slide#88]
Currently the docs almost emit documentation for the `num_traits` crate:

https://slide-dev.ayazhafiz.com/num_traits/index.html

We should get rid of this

**Comment by luke-bhan** [comment]
num_traits still appears on crates. will fix when I get a min.

**Comment by ayazhafiz** [comment]
No, the token was just bad. Should be fixed now; I'll keep an eye on the token in case it acts up again.
