### ISSUE TITLE
a + 1 - 1 doesn't simplify

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/slide#92]
Should go to a, goes to a + 1 - 1.

**Comment by luke-bhan** [comment]
I think this could be defined as a rule 
literal - literal  = 0

**Comment by ayazhafiz** [comment]
@luke-bhan I'll assign this to you then

**Comment by ayazhafiz** [comment]
Actually the additive inverse is already a rule so the work that needs to be done here is a little bit different.  I think `a + 1 - 1` is getting parsed as `(- (+ a 1) 1)` and we're currently not smart enough to unroll it as needed. I'm going to readd an S-expression debug form so this is easier to see.

**Comment by ayazhafiz** [comment]
@luke-bhan are you working on this?

**Comment by luke-bhan** [comment]
Not currently. I'm writing the heuristic poly rn so if you wanna do this thats perfect.

**Comment by ayazhafiz** [comment]
sounds good

________________________________
От: Luke Bhan <notifications@github.com>
Отправлено: Saturday, June 6, 2020 3:24:50 PM
Кому: ayazhafiz/slide <slide@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Author <author@noreply.github.com>
Тема: Re: [ayazhafiz/slide] a + 1 - 1 doesn't simplify (#92)


Not currently. I'm writing the heuristic poly rn so if you wanna do this thats perfect.

**Comment by ayazhafiz** [comment]
Leaving this open till I add docs for the commit I made
